FROM mcr.microsoft.com/playwright:v1.49.1-jammy

WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install --omit=dev

COPY . .
ENV NODE_ENV=production
EXPOSE 8080
CMD ["node", "index.js"]
